[general]
enabled=yes
bindaddr=127.0.0.1
bindport=8088
tlsenable=yes
tlsbindaddr=0.0.0.0:8089
tlscertfile=/run/credentials/tls/tls.crt
tlsprivatekey=/run/credentials/tls/tls.key
tlsdisablev1=yes
tlsdisablev11=yes
